(function(){
  const DISTRIBUTION={'第1章':5,'第2章':5,'第3章':5,'第4章':10,'第5章':5}; const HISTORY_KEY='touhan.engine.generator.history.v042';
  function hashSeed(text){let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0} function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}} function shuffle(list,random){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function history(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return[]}} function recentIds(days=4){return new Set(history().slice(-days).flatMap(x=>x.questionIds||[]))}
  function pick(pool,count,random,blocked,selected){const years={};for(const q of pool)(years[q.year]??=[]).push(q);Object.keys(years).forEach(y=>years[y]=shuffle(years[y],random));const ys=shuffle(Object.keys(years),random),out=[];let c=0,g=0;while(out.length<count&&ys.length&&g++<10000){const y=ys[c++%ys.length];let q;while(years[y].length&&!q){const x=years[y].shift();if(!selected.has(x.question_id)&&!blocked.has(x.question_id))q=x}if(q){out.push(q);selected.add(q.question_id)}if(ys.every(k=>years[k].length===0))break}return out}
  function toAppQuestion(q,no){return {no,chapter:q.chapter,theme:`東京都${q.year}年度 問${q.question_no}`,knowledge_id:q.question_id,source:`過去問（東京都${q.year}年度 問${q.question_no}）`,question_type:'single_best',text:String(q.question_text).trim(),choices:q.choices.map((text,i)=>({id:String(i+1),text})),answer:String(q.answer),explanation:`正答は${q.answer}です。東京都${q.year}年度の公式過去問です。`}}
  function generate({questions,date,dayId,title}){if(!Array.isArray(questions)||questions.length<120)throw new Error(`使用可能問題が不足しています（${questions?.length||0}問）`);const random=rng(hashSeed(`${date}|${dayId}|${questions.length}`)),blocked=recentIds(3),selected=new Set(),sets=[];
    for(let s=1;s<=4;s++){const picked=[];for(const [chapter,count] of Object.entries(DISTRIBUTION))picked.push(...pick(questions.filter(q=>q.chapter===chapter),count,random,blocked,selected));if(picked.length<30){for(const q of shuffle(questions,random)){if(picked.length>=30)break;if(!selected.has(q.question_id)&&!blocked.has(q.question_id)){picked.push(q);selected.add(q.question_id)}}}if(picked.length<30)throw new Error(`第${s}セットを30問確保できませんでした`);sets.push({id:`${dayId}-set-${s}`,title:`第${s}セット`,note:`全120問中 ${s}/4`,questions:shuffle(picked,random).map((q,i)=>toAppQuestion(q,i+1))})}
    const result={id:dayId,title,date:date.replace(/-/g,'/'),category:'exam_style',category_label:'本番形式',sets};const ids=sets.flatMap(s=>s.questions.map(q=>q.knowledge_id));const rows=history().filter(x=>x.dayId!==dayId);rows.push({dayId,date,resultTitle:title,questionIds:ids,createdAt:new Date().toISOString()});localStorage.setItem(HISTORY_KEY,JSON.stringify(rows.slice(-30)));return result}
  window.TouhanGenerator={generate,DISTRIBUTION,HISTORY_KEY};
})();